disabled_rules:
  - trailing_comma
  - opening_brace
  - modifier_order

opt_in_rules:
  # Correctness
  - empty_count
  - contains_over_first_not_nil
  - contains_over_filter_count
  - first_where
  - last_where
  - sorted_first_last
  - flatmap_over_map_reduce
  - array_init
  - toggle_bool
  - legacy_multiple
  - yoda_condition
  # Safety
  - force_unwrapping
  - implicitly_unwrapped_optional
  - fatal_error_message
  - overridden_super_call
  - unavailable_function
  # Style
  - closure_spacing
  - closure_end_indentation
  - redundant_nil_coalescing
  - redundant_type_annotation

excluded:
  - .build
  - Package.swift

line_length:
  warning: 120
  error: 150
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 25
  error: 40

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
